### ISSUE TITLE
snpinfo_1kg_hm3 filter

### ISSUE THREAD

**Issue by hxchengtj** [getian107/PRScs#21]
Hi Tian,

SUM_STATS_FILE and VALIDATION_BIM_PREFIX format
many thanks,

h.

**Comment by getian107** [comment]
No- SUM_STATS_FILE and VALIDATION_BIM_PREFIX don't need to be filtered to the same SNPs or HapMap3 SNPs; PRScs will automatically select shared SNPs between the reference panel, GWAS summary statistics and the target dataset. VALIDATION_BIM_PREFIX refers to the dataset for the target sample (where the performance of PRS is evaluated). You are correct that the target dataset is used after running PRScs. You need to use the posterior SNP effect sizes estimated by PRScs to weight the genotypes in the target set in order to calculate the PRS.

**Comment by hxchengtj** [comment]
Thanks! also, A/T or C/G SNPs can be included in SUM_STATS_FILE and VALIDATION_BIM_PREFIX right?

**Comment by getian107** [comment]
Yes- the software will take care of strand ambiguous SNPs.
