### ISSUE TITLE
Use proper CSV reader?

### ISSUE THREAD

**Issue by jpsamaroo** [getian107/PRScs#28]
Currently, PRScs assumes a fixed column order for input files. This is prone to bugs, as it's possible that the user's column ordering is not what PRScs currently expects (and led my colleague and I into a 3+ month goose chase trying to determine why our PRS scores were so terrible for a given dataset).

I therefore propose using a bona-fide CSV reader for PRScs, which should alleviate this issue, as modern CSV readers parse the (optional) CSV header to determine the location of columns. I'm not familiar with the Python ecosystem so I can't make any recommendations for *which* CSV reader to use, but I do believe using any well-maintained reader would be better than our current approach (and might even lead to performance gains, since CSV readers tend to also be well optimized for reading performance).

Note that this is the approach taken by https://github.com/fauconab/PRS.jl, which did not exhibit this bug because the CSV reader (https://github.com/JuliaData/CSV.jl) parses the header to determine column ordering.

CC @fauconab

**Comment by getian107** [comment]
Hi- thanks for the comments. I agree that requiring a fixed column order for input files is not optimal in terms of storage and efficiency. I used to include flags that can be used to specify column contents so that users don't need to reformat the summary statistics. But this produced numerous issues when parsing different summary statistics files (e.g., weird format, unusual strings or delimiters, missing data in certain columns, misspecification of beta or OR, etc). I therefore intensionally used a fixed column format for the input files so that users need to look into the data more carefully in order to reformat the summary statistics, which I think reduces errors.
