### ISSUE TITLE
LD reference panel for UK Biobank analyses

### ISSUE THREAD

**Issue by cnl27** [getian107/PRScs#67]
Hello,

Just a quick question. I know it probably does not have a great impact on the results, but, for analysis using UK Biobank data, would it have any advantage to use the UK Biobank LD reference panel? Or would it be better to actually use the one from the 1000 Genomes Project so that the datasets are independent?

Thank you.

**Comment by getian107** [comment]
Hi - Ideally you would use the reference panel that matches the discovery GWAS sample. The target sample is usually not relevant to the choice of reference panels. Therefore if the discovery GWAS was performed in UK Biobank or included UK Biobank samples, using the UK Biobank LD reference may slightly improve prediction relative to the 1000 Genomes reference. Otherwise in the most cases the two reference panels should have comparable performance.

**Comment by cnl27** [comment]
Thank you for your answer!
