### ISSUE TITLE
Can PRS-CS be used for estimating the PRS for the X chromosome?

### ISSUE THREAD

**Issue by xliaoyi** [getian107/PRScs#85]
Hi there,

I am interested in estimating PRS for the X chromosome. However, I noticed in the README that only the autosomes were mentioned. Could you please clarify whether PRS-CS can be applied to the X chromosome as well?

Thank you for your help!

Best regards,
Louis

**Comment by getian107** [comment]
Hi Louis -- The current version of PRS-CS cannot be applied to the X chromosome. Additional work will be needed to parse X chr summery statistics and build an X chr reference panel.

**Comment by xliaoyi** [comment]
Hi Tian,

Thank you for your prompt reply! May I ask some naive questions: 

1. why is the X chromosome tricky for PRS estimation? 

2. If PRS-CS cannot be applied to the X chromosome, does the P+T method work for the X chromosome? According to my intuition, as long as I have the dosage and effect size of each allele, I can use the P+T method for any chromosome, including the X chromosome. I believe there may be some implicit factors I haven’t considered. Please correct me if I’m wrong.

Thanks,
Louis

**Comment by getian107** [comment]
Hi Louis -- X chromosome is a little tricky because males have one copy and females have two copies of X chromosomes. Therefore they may need to be treated separately (e.g., in males genotypes are no longer 0, 1, 2 but should be coded as 0 and 2). There also seems to be some inconsistencies in the literature regarding how effect sizes in males are estimated (coding genotypes as 0 and 1 vs. 0 and 2). These may affect how reference panels are built. There may be other issues such as pseudoautosomal regions that need to be removed or handled with caution. These all add some complexities to the PRS construction on the X chromosome, although in principle all PRS methods can be adapted to model the X chromosome. There is also no clear evidence so far to show the importance of including X chromosome to improve prediction accuracy. I guess that's also one of the reasons that X chromosome has not been included in most PRS studies.

**Comment by xliaoyi** [comment]
Thank you so much for telling me this, Tian! If I only want to estimate PRS for males, and I’ve coded male genotypes as 0 and 2 while removing pseudoautosomal regions, do you think I can use the P+T method in this situation?

**Comment by getian107** [comment]
Yes I think you can.

**Comment by xliaoyi** [comment]
Thank you so much for your time in helping me with my naive questions. I truly appreciate it!
